### PR TITLE
Fix position tracking after SDK update

### LINKED ISSUE #3641: Tracking file could not be opened for reading
Hello,
Tracking worked 2024-10-01 and before on my phone, since 2024-10-02 it doesn't.

When I activate tracking, time starts running but distance remains 0, no yellow line and this shows up. 

"Mergin maps crashes repeatedly" It doesn't close the app, 
Image

I have tried to factory reset my phone, same issue. All my projects works on other devices.
Any Ideas? Thank you.

### PR DESCRIPTION
**Pull request by VitorVieiraZ**
Handling newly required permissions after SDK update from version 33 to 34.

Fixes #3641

### CODE REVIEW

File: app/android/src/uk/co/lutraconsulting/PositionTrackingBroadcastMiddleware.java [hunk 1]
```diff
@@ -46,7 +47,12 @@ public void registerBroadcastReceiver( Context context ) {
         intentFilter.addAction( TRACKING_ALIVE_STATUS_ACTION );
 
         // Set this as the receiver of POSITION_UPDATE and STATUS_MESSAGE intent actions
-        context.registerReceiver( serviceMessageReceiver, intentFilter );
+        if ( Build.VERSION.SDK_INT >= 34 ) { // Android 14 ( Upside Down Cake )
+            context.registerReceiver( serviceMessageReceiver, intentFilter, Context.RECEIVER_EXPORTED );
```
Comment (tomasMizera) [inline app/android/src/uk/co/lutraconsulting/PositionTrackingBroadcastMiddleware.java:51]: Hmm, here we say that the broadcast is exported, but in the manifest we declared the service to not be exported. This works, but we might want to unify these (or keep it in mind) when finalizing https://github.com/MerginMaps/mobile/pull/3490

**Review by tomasMizera — APPROVED** [review]
Great, thanks for preparing this one!

**Comment by tomasMizera** [comment]
iOS CI will fix once merged
