### PR TITLE
Fix permanently pending synchronization issue for projects with selective sync enabled

### LINKED ISSUE #3129: Project with selective sync enabled keeps requesting sync
To reproduce:
 - Download project `tomas/general` from the app.dev server
 - You will see that the project status says there are pending changes
 - Click sync
 - The same status remains

A quick debugging session revealed that it is because `localFiles.count() != oldServerFiles.count()` in the `MerginApi::hasLocalChanges`. These are the logs:

```
local: 12
 - "mergin-config.json"
 - "building-photos.gpkg"
 - "survies.gpkg"
 - "layers.gpkg"
 - "buildings (edit conflict, tomas v64).json"
 - "layers (conflicted copy, tomas v64).gpkg"
 - "paths.gpkg"
 - "building-photos/pexels-yassin-doukhane-2570446.jpg"
 - "tracking_layer.gpkg"
 - "project.qgz"
 - "building-photos/20240201_093946.jpg"
 - "buildings.gpkg"
old server: 13
 - "project.qgz"
 - "layers.gpkg"
 - "mergin-config.json"
 - "tracking_layer.gpkg"
 - "paths.gpkg"
 - "photos/Screenshot 2024-01-13 at 22.02.53.png"
 - "building-photos.gpkg"
 - "buildings.gpkg"
 - "survies.gpkg"
 - "building-photos/pexels-yassin-doukhane-2570446.jpg"
 - "layers (conflicted copy, tomas v64).gpkg"
 - "building-photos/20240201_093946.jpg"
 - "buildings (edit conflict, tomas v64).json"
```

The file that is missing is "photos/Screenshot...png" - it might have something to do with selective sync. Selective sync is enabled for folder `./photos`. 

image

### PR DESCRIPTION
**Pull request by VitorVieiraZ**
Files listed on the server are now filtered before retrieving local changes status, ensuring that files excluded by selective sync are not compared. This prevents a permanent pending sync status when selective sync is enabled.

Resolves #3129

### CODE REVIEW

File: core/merginapi.cpp [hunk 1]
```diff
@@ -2994,14 +2994,23 @@ bool MerginApi::hasLocalChanges(
   const QString &projectDir
 )
 {
-  if ( localFiles.count() != oldServerFiles.count() )
+  MerginConfig config = MerginConfig::fromFile( projectDir + "/" + sMerginConfigFile );
```
Comment (PeterPetrik) [inline core/merginapi.cpp:2997]: we need unit tests

**Review by PeterPetrik — APPROVED** [review]

**Comment by PeterPetrik** [comment]
please rebase with master (cppcheck fix)

File: core/merginapi.cpp (hunk 1 above)
Comment (tomasMizera) [inline core/merginapi.cpp:2997]: There is a flag in `MerginApi` called `supportsSelectiveSync`. The code we add here should execute only if Mergin Api is set to use selective sync.

**Review by tomasMizera — CHANGES_REQUESTED** [review]
Just the simple `if` is missing, otherwise I think this lookd good 👍🏻

File: app/test/testmerginapi.cpp [hunk 2]
```diff
@@ -3116,3 +3116,112 @@ void TestMerginApi::testDownloadWithNetworkErrorRecovery()
...
+  // 3 => empty file
+  tempFilePath = QDir::tempPath() + "/test_empty_config.json";
+  {
+    QFile file( tempFilePath );
+    QVERIFY( file.open( QIODevice::WriteOnly ) );
+    file.write( "" );
+    file.close();
+  }
+  config = MerginConfig::fromFile( tempFilePath );
+  QVERIFY( !config.isValid );
```
Comment (tomasMizera) [inline app/test/testmerginapi.cpp:3162]: I'd prefer if we also checked `QCOMPARE( config.selectiveSyncEnabled, false );` to make sure that we won't have it `true` in such cases.

File: app/test/testmerginapi.cpp [hunk 3]
```diff
@@ -3116,3 +3116,112 @@ void TestMerginApi::testDownloadWithNetworkErrorRecovery()
...
+  QFile::remove( tempFilePath );
+
+  // 4 => file-not-found
+  tempFilePath = QDir::tempPath() + "/nonexistent_config.json";
+  config = MerginConfig::fromFile( tempFilePath );
+  QVERIFY( !config.isValid );
```
Comment (tomasMizera) [inline app/test/testmerginapi.cpp:3168]: Same here (please check `config.selectiveSyncEnabled`)

File: app/test/testmerginapi.cpp [hunk 4]
```diff
@@ -3116,3 +3116,112 @@ void TestMerginApi::testDownloadWithNetworkErrorRecovery()
...
+  // the checksum of "data.txt" is different, and local changes should be detected
+  QList<MerginFile> localFilesChanged;
+  {
+    MerginFile modifiedIncluded = serverIncluded;
+    modifiedIncluded.checksum = "different_checksum";
+    localFilesChanged.append( modifiedIncluded );
+  }
+
+  result = mApi->hasLocalChanges( oldServerFiles, localFilesChanged, projectDir, config );
+  QVERIFY( result );
```
Comment (tomasMizera) [inline app/test/testmerginapi.cpp:3225]: It would be good to also test the `MerginApi::hasLocalProjectChanges` method. We need to verify that it reads the correct config file and all works as expected. I suggest to create a new test function for that. We could create a new project, update some files, runs this method and check the result. Mind that we need to cover scenarios like - a) selective sync (dis-)enabled, b) there are (not) some local changes

**Review by tomasMizera — APPROVED** [review]
Just update the tests please and we can merge this :) Thanks

File: app/test/testmerginapi.cpp [hunk 5]
```diff
@@ -3116,3 +3116,195 @@ void TestMerginApi::testDownloadWithNetworkErrorRecovery()
...
+}
+
+void TestMerginApi::testHasLocalProjectChanges()
```
Comment (tomasMizera) [inline app/test/testmerginapi.cpp:3231]: Interesting approach to generate project metadata here in test. Let's see if it will work fine in future, I think we can merge it now :)

**Review by tomasMizera — APPROVED** [review]

**Review by harminius — APPROVED** [review]
Verified, works as expected on Android :green_book:
