### PR TITLE
Fix deletion of multiple features

### LINKED ISSUE #4097: Feature to delete multiple selected features at once
Add "delete/remove" button as an option when selecting multiple features at once. The button can be in the row, next to the "edit" button.

Image

It seems like there is also no "breathing space" between the row of buttons and system buttons. Let's unify the visual with Figma design.

Figma link: https://www.figma.com/design/d78a4ehBBgK6MyxCTuCAqg/Mobile-App?node-id=4233-18310&t=KOzmmky17djKv0q1-4

### PR DESCRIPTION
**Pull request by gabriel-bolbotina**
Fixed issue when deleting multiple features for the second time, as described in this comment:
https://github.com/MerginMaps/mobile/issues/4097#issuecomment-3570562912

fixes #4097

### CODE REVIEW

File: app/multieditmanager.cpp [hunk 1]
```diff
@@ -182,6 +182,8 @@ void MultiEditManager::deleteSelectedFeatures()
     mModel->populate( {} );
     mLayer->triggerRepaint();
     CoreUtils::log( QStringLiteral( "Multi Edit Manager" ), QStringLiteral( "Deleted %1 features from %2" ).arg( fids.size() ).arg( mLayer->name() ) );
+    // commit the changes to stop editing the layer
+    mLayer->commitChanges();
```
Comment (tomasMizera) [inline app/multieditmanager.cpp:184]: I think it is better to first commit and then trigger repaint
