### PR TITLE
Fix photo naming

### LINKED ISSUE #3035: Check if photo names contain invalid characters
A user reported inability to download their project to desktop after it was uploaded from a mobile device.
We have found out some photo names include "\n" or 0x0a that later breaks download attempts from the service.

See the following for more details
https://gitlab.lutraconsulting.co.uk/ops/operations/-/issues/88#note_36853

### LINKED ISSUE #3709: Photos in wrong folder with wrong name(?)
In not infrequent that despite having the project set to store photos in a specific folder with a specific name

Image

photos are being saved in the project folder with a name that seems to be the one given by default by the camera app of the device

Image

anyway the path stored in the attribute table is correct, and this photos are not ones that have been added in the form.

### LINKED ISSUE #3762: Avoid using forbiden characters in photo names
When the app is renaming an image, we should double-check if the name would be accepted on the server. If not, we should sanitize the name to allow sync.

See https://github.com/MerginMaps/qgis-plugin/issues/678#issuecomment-2746300074

### PR DESCRIPTION
**Pull request by uclaros**
- Make sure that photos end up in the correct path, combination of _Default Path_ and _custom photo name_
- Make sure the path stored in the feature field respects the _absolute/relative to Project Path/Default Path_ setting
- Sanitize Default paths and photo filenames, replacing invalid chars with `_`
- Allow using field alias in custom photo name expression

Fix #3762
Should fix #3709 
Should fix #3035

### CODE REVIEW

File: app/inpututils.cpp [hunk 1]
```diff
@@ -69,6 +69,7 @@
 
 static const QString DATE_TIME_FORMAT = QStringLiteral( "yyMMdd-hhmmss" );
 static const QString INVALID_DATETIME_STR = QStringLiteral( "Invalid datetime" );
+const thread_local QRegularExpression ILLEGAL_FILENAME_CHARS( QStringLiteral( "[\x00-\x20<>:|?*\"]" ) );
```
Comment (tomasMizera) [inline app/inpututils.cpp]: Is this the same logic as on server?

File: app/inpututils.cpp [hunk 2]
```diff
@@ -1961,6 +1964,11 @@ QUrl InputUtils::iconFromGeometry( const Qgis::GeometryType &geometry )
   }
 }
 
+void InputUtils::sanitizeFileName( QString &fileName )
+{
+  fileName.replace( ILLEGAL_FILENAME_CHARS, QStringLiteral( "_" ) );
```
Comment (tomasMizera) [inline app/inpututils.cpp]: Can we also trim the `fileName`?

File: app/test/testattributecontroller.cpp [hunk 3]
```diff
@@ -718,30 +725,182 @@ void TestAttributeController::testPhotoRenaming()
...
+  }
 
-  QVERIFY( !QFile::exists( projectDir + QStringLiteral( "/photo2.jpg" ) ) );
-  QVERIFY( QFile::exists( projectDir + QStringLiteral( "/photos/Survey.jpg" ) ) );
-  QCOMPARE( controller.featureLayerPair().feature().attribute( 4 ), QVariant( "photos/Survey.jpg" ) );
+  // TODOs:
+  //  - report that people should not use feature IDs in custom photo names!
+  //  - fix issue where email might be used for mm_username variable as this breaks the renaming!
+  //  - fix docs recommending variables with old prefix for photo names
+  //  - report misconfiguration of the use of subfolders & subfolders in the photo naming
```
Comment (tomasMizera) [inline app/test/testattributecontroller.cpp]: I think we can remove this now

File: app/inpututils.cpp (hunk 1 above)
Comment (uclaros) [reply app/inpututils.cpp]: On server the [pathvalidate](https://github.com/thombashi/pathvalidate) python library is used, which does an extensive validation.

I believe with this simplistic approach we're addressing 99% of common use cases

File: app/test/testattributecontroller.cpp (hunk 3 above)
Comment (uclaros) [reply app/test/testattributecontroller.cpp]: Or move them to plugin repo :)

Is the email a real issue though? Emails should not have illegal characters for a filename!

File: app/inpututils.cpp (hunk 2 above)
Comment (uclaros) [reply app/inpututils.cpp]: This is slightly tricky!
Should we trim before the file extension? After? Both?
We're using this method to also sanitize the Default Path, which doesn't have an extension, but if it has a `.` we should not trim before it!

File: app/test/testattributecontroller.cpp (hunk 3 above)
Comment (tomasMizera) [reply app/test/testattributecontroller.cpp]: - `report misconfiguration of the use of subfolders & subfolders in the photo naming` this is not relevant anymore
- `fix docs recommending variables with old prefix for photo names` this is merged in docs
- `fix issue where email might be used for mm_username variable as this breaks the renaming!` this is fixed as we now cache the email (works even  offline)
- `report that people should not use feature IDs in custom photo names!` I believe we say this in docs :)

File: app/test/testattributecontroller.cpp [hunk 4]
```diff
@@ -718,30 +725,186 @@ void TestAttributeController::testPhotoRenaming()
...
+  // Attachment fields:
+  // 3 - photo
+  // 4 - photo_with_slash
+  // 5 - photo_in_subfolder_relative_to_project_path -> subfolder 'media'
+  // 6 - photo_in_subfolder_relative_to_default_path -> subfolder 'media'
+  // 7 - photo_with_slash_in_subfolder_relative_to_project_path -> subfolder 'media/with_slash'
+  // 8 - photo_with_slash_in_subfolder_relative_to_default_path -> subfolder 'media/with_slash'
+  //
+
+  controller.setFormValue( items.at( 2 ), QStringLiteral( "mynotes" ) );
```
Comment (tomasMizera) [inline app/test/testattributecontroller.cpp]: How about testing the trimming too?
```suggestion
  controller.setFormValue( items.at( 2 ), QStringLiteral( "mynotes " ) );
```

**Review by tomasMizera — APPROVED** [review]
Looks good! 🚀

**Comment by tomasMizera** [comment]
Unrelated iOS CI failure
