### PR TITLE
Minimal fix for reuse last value

### LINKED ISSUE #3784: Reusing last entered value is broken
The feature for auto-filling field with value from the previously recorded feature does not work for me.

Hope I get how it should work
Scenario:
1. Enable Reuse last entered value feature for a project in its Settings
2. Record a feature, check the checkbox for an attribute and fill it in
3. Record another feature which should have the checked fields prefilled

https://github.com/user-attachments/assets/76f26e01-c415-400a-b8d5-7690ed459214

### PR DESCRIPTION
**Pull request by uclaros**
Minimal fix for #3784

Fix #3784

### CODE REVIEW

File: app/attributes/rememberattributescontroller.h [hunk 1]
```diff
@@ -68,9 +72,10 @@ class  RememberAttributesController : public QObject
     };
 
     bool mRememberValuesAllowed = false;
-    //! Remembered last created feature for each layer (key)
-    QHash<QString, RememberedValues> mRememberedValues;
+    //! Remembered last created feature for each project/layer (key)
+    static QHash<QString, RememberedValues> sRememberedValues;
```
Comment (PeterPetrik) [inline app/attributes/rememberattributescontroller.h:76]: why there is need for static variable?

Comment (uclaros) [reply app/attributes/rememberattributescontroller.h:76]: A `RememberAttributesController` is instantiated with each forms' `AttributeController`, so we need the storage to persist. We agreed with a static var instead of QSettings for now.

**Review by tomasMizera — APPROVED** [review]
