### PR TITLE
Fix android image picker

### LINKED ISSUE #2831: Use new photo picker on Android
We are using intent of type `ACTION_PICK` to pick images from gallery. This is way of picking images is deprecated and soon blocked on Google Play. We need to migrate to `ACTION_GET_CONTENT`.

There is a new native (nice!) photo/video picker - `PhotoPicker` (see https://developer.android.com/training/data-storage/shared/photopicker). We can not use it directly though as it uses Android fragments. However, android _should_ open the new picker even with `ACTION_GET_CONTENT` intent!

Additionally, we should not need to ask for storage permissions.

Read more in the parent ticket and:
 - https://medium.com/androiddevelopers/permissionless-is-the-future-of-storage-on-android-3fbceeb3d70a
 - https://android-developers.googleblog.com/search/label/PickVisualMedia?max-results=12

### PR DESCRIPTION
**Pull request by Withalion**
Fixes #2831 

GPC requires apps to use the newer API and banned the use of `READ_MEDIA_IMAGES` permission. We use the intent `ACTION_GET_CONTENT` which triggers system image picker.

It has been tested on android 14. The image picker and location metadata works. Needs to be tested on android < 13.

### CODE REVIEW

**Review by harminius — COMMENTED** [review]
I don't have Android < 13. Leaving the testing for @tomasMizera, thanks.

**Comment by Withalion** [comment]
Tested on Android 14 both GMS and non-GMS and Android 9 both GMS and non-GMS.
On non-GMS Android 14 the metadata don't get replicated into form.

**Comment by Withalion** [comment]
Finally everything works on android 9, 11, 14 🎉 We still keep getting only local images, but fetching cloud images should not be much effort to add.

**Comment by RastoHu** [comment]
I took few pictures with coordinates and after uploading the photos to mergin maps app, the coordinates are missing in mobile app. Also in plugin are NULL values in coordinates fields after sync.
Input App: 2025.2.5 - ndroid (662311)
System: Android 14.0
Device: Redmi A3

**Comment by Withalion** [comment]
@RastoHu after checking the debug log, it looks like there is an issue with reading EXIF metadata from this device (maybe the change of architecture might be the culprit), the same photo worked with no issues on other device

Debug log:
```
D/EXIF Utils(28017): getEXIFAttribute: /storage/emulated/0/Android/data/uk.co.lutraconsulting/files/projects/pictures-test/1000000030.jpg - GPSLongitude
D/EXIF Utils(28017): getEXIFdata: /storage/emulated/0/Android/data/uk.co.lutraconsulting/files/projects/pictures-test/1000000030.jpg to file: 
D/EXIF Utils(28017): getEXIFdata: GPSLongitude -> 0/1,0/1,0/1
D/EXIF Utils(28017): getEXIFAttribute: /storage/emulated/0/Android/data/uk.co.lutraconsulting/files/projects/pictures-test/1000000030.jpg - GPSLatitude
D/EXIF Utils(28017): getEXIFdata: /storage/emulated/0/Android/data/uk.co.lutraconsulting/files/projects/pictures-test/1000000030.jpg to file: 
D/EXIF Utils(28017): getEXIFdata: GPSLatitude -> 0/1,0/1,0/1
D/EXIF Utils(28017): getEXIFAttribute: /storage/emulated/0/Android/data/uk.co.lutraconsulting/files/projects/pictures-test/1000000030.jpg - GPSImgDirection
D/EXIF Utils(28017): getEXIFdata: /storage/emulated/0/Android/data/uk.co.lutraconsulting/files/projects/pictures-test/1000000030.jpg to file: 
D/EXIF Utils(28017): getEXIFdata: GPSImgDirection -> null
```

File: app/android/src/uk/co/lutraconsulting/InputActivity.java [hunk 1]
```diff
@@ -143,31 +153,88 @@ public boolean openFile( String filePath ) {
...
+        cursor.close();
+      }
+    }
+    if (result == null) {
+      result = uri.getPath();
+      int cut = result.lastIndexOf('/');
+      if (cut != -1) {
+        result = result.substring(cut + 1);
+      }
+    }
```
Comment (tomasMizera) [inline app/android/src/uk/co/lutraconsulting/InputActivity.java:236]: What's this doing? Can you add a comment please?

File: app/androidutils.cpp [hunk 2]
```diff
@@ -297,13 +285,17 @@ bool AndroidUtils::requestCameraPermission()
 bool AndroidUtils::requestMediaLocationPermission()
 {
 #ifdef ANDROID
+  const double buildVersion = QSysInfo::productVersion().toDouble();
   // ACCESS_MEDIA_LOCATION is a runtime permission without UI dialog (User do not need to click anything to grant it, it is granted automatically)
-  return checkAndAcquirePermissions( "android.permission.ACCESS_MEDIA_LOCATION" );
+  if ( buildVersion < ANDROID_VERSION_13 )
+  {
+    return checkAndAcquirePermissions( "android.permission.ACCESS_MEDIA_LOCATION" );
```
Comment (tomasMizera) [inline app/androidutils.cpp:292]: Given this change, we should test EXIF also for camera (cc @RastoHu )

Comment (RastoHu) [reply app/androidutils.cpp:292]: tested, OK

File: app/android/src/uk/co/lutraconsulting/InputActivity.java (hunk 1 above)
Comment (Withalion) [reply app/android/src/uk/co/lutraconsulting/InputActivity.java:236]: fixed
