### PR TITLE
Fix photo sketching bugs

### LINKED ISSUE #4056: Photo sketch editing rotates images unexpectedly (orientation changes after adding sketches)
**Description**
Photo orientation changes immediately after adding and saving a sketch annotation on a photo in a point feature.

**Environment**
Staging

**Application (+ app version, build, operating system)**
- Mobile app version: 2025.6.0

**Steps to reproduce**
1. In the mobile app open project `tester-ws-1/test_photo-sketches`.
2. Create a new feature in layer `point_photo_layer`; add photo; save.
3. Edit the feature; open photo; enter sketch mode; add a sketch; save sketch.
5. Observe that the orientation of photos changed.

**Actual results**
Photo(s) display with changed / incorrect orientation after sketch is added.

**Expected results**
Original photo orientation is preserved.

**Screenshots or logs**

**Conclusion**
*Created by GitHub Copilot and supervised by a human test analyst.*

### LINKED ISSUE #4057: First photo sketch missing after sync while second photo sketch persists
**Description**
After adding sketches to two photos in the same point feature, synchronizing causes the first photo’s sketch to disappear while the second photo’s sketch remains.

**Environment**
Staging

**Application (+ app version, build, operating system)**
- Mobile app version: 2025.6.0

**Steps to reproduce**
1. In the mobile app open project `tester-ws-1/test_photo-sketches`.
2. Create a new feature in layer `point_photo2_layer`; add two photos; save.
3. Edit the feature; add a sketch to each of the two photos; save each sketch and then save the feature. DO NOT SCROLL UP BACK TO FIRST PHOTO!
4. Synchronize the project.
5. Check the photos in MM plugin.

**Actual results**
Sketch on the first photo is missing; sketch on the second photo remains after opening the photos in Mergin Maps plugin.

**Expected results**
All saved sketches persist for every photo after saving and synchronization.

**Screenshots or logs**
(Not provided)

**Conclusion**
*Created by GitHub Copilot and supervised by a human test analyst.*

### PR DESCRIPTION
**Pull request by Withalion**
fixes #4057 
fixes #4056 (I didn't observe this bug anymore, it might be a side effect from the other bug)

- photo sketches now get saved into project subfolder in `temp`
- photo sketches get saved to original by `AttributeController` instead of `PhotoSketchingController`
- rework tests

### CODE REVIEW

File: app/attributes/attributecontroller.cpp
Comment (tomasMizera) [inline app/attributes/attributecontroller.cpp:1]: Let's make sure we test this in all the combinations of custom photo names and subfolders ⚠️

File: app/qml/form/editors/MMFormPhotoEditor.qml [hunk 1]
```diff
@@ -158,6 +158,7 @@ MMFormPhotoViewer {
 
     PhotoSketchingController {
```
Comment (tomasMizera) [inline app/qml/form/editors/MMFormPhotoEditor.qml:159]: I think the `PhotoSketchingController` could now live inside `sketchingLoader` in `MMFormPhotoViewer`, couldn't it? We do not seem to need to do anything here.

Comment (Withalion) [reply app/qml/form/editors/MMFormPhotoEditor.qml:159]: I don't think so, we use it in callbacks (which might not be necessary), but we reference something that is not available in `MMFormPhotoViewer`

Comment (tomasMizera) [reply app/qml/form/editors/MMFormPhotoEditor.qml:159]: What I meant is that we do not need to perform the operations we do here (`.clear()`) if we simply move it to the loader

**Review by tomasMizera — APPROVED** [review]
