### PR TITLE
fix centering when preview panel is opened

### LINKED ISSUE #3260: Center map extent when feature is identified
ISS-150, reported by @PeterPetrik 

When I click on identify - the map is centered, but the drawer overflows the center point, the selected point should be probably in the top part so is visible?

### PR DESCRIPTION
**Pull request by uclaros**
Fixes #3260

- Preview panel height is taken into account when centering to the identified feature
- Animation is used while centering
- If _follow gps_ was enabled, map pans back to gps position after closing the preview panel

### CODE REVIEW

File: app/inpututils.cpp [hunk 1]
```diff
@@ -277,6 +277,19 @@ void InputUtils::setExtentToFeature( const FeatureLayerPair &pair, InputMapSetti
   mapSettings->setExtent( currentExtent );
 }
 
+QPointF InputUtils::geometryCenterToScreenCoordinates( const QgsGeometry &geom, InputMapSettings *mapSettings )
+{
+  QPointF screenPoint;
+
```
Comment (tomasMizera) [inline app/inpututils.cpp:283]: Please add check for validity of the `mapSettings` pointer

File: app/qml/main.qml
Comment (tomasMizera) [inline app/qml/main.qml:1]: Do we still need to calculate `takenVerticalSpace` property of `MMFormsStackController` and consider it when evaluating the `mapExtentOffset` of `MMMapController`?

File: app/qml/map/MMMapController.qml [hunk 2]
```diff
@@ -1183,6 +1188,11 @@ Item {
       }
 
       case "view": {
+        if ( identifyHighlight.geometry !== null )
```
Comment (tomasMizera) [inline app/qml/map/MMMapController.qml:1191]: Can you add an explanation comment here please?

File: app/inpututils.cpp (hunk 1 above)
Comment (uclaros) [reply app/inpututils.cpp:283]: whoops!

File: app/qml/map/MMMapController.qml (hunk 2 above)
Comment (uclaros) [reply app/qml/map/MMMapController.qml:1191]: sure

File: app/qml/main.qml
Comment (uclaros) [reply app/qml/main.qml:1]: This is also used for the conditional visibility of the accuracy button:
```
          visible: {
            if ( root.mapExtentOffset > 0 && root.state !== "stakeout" ) return false
```

the actual value is not used, so it could be replaced by some other means. However, it's probably a good idea to keep the mapExtentOffset updated so that it always holds the correct map's offset.

**Comment by uclaros** [comment]
What's also not used any more is the `considerMapExtentOffset` parameter in 
```qml
  function centerToPair( pair, considerMapExtentOffset = false ) {
    if ( considerMapExtentOffset )
      var mapExtentOffsetRatio = mapExtentOffset / mapCanvas.height
    else
      mapExtentOffsetRatio = 0

    __inputUtils.setExtentToFeature( pair, mapCanvas.mapSettings, mapExtentOffsetRatio )
  }
```
and the relevant code in `InputUtils::setExtentToFeature()` 
Should I remove those?

**Comment by tomasMizera** [comment]
> What's also not used any more is the `considerMapExtentOffset` parameter in
> 
> ```qml
>   function centerToPair( pair, considerMapExtentOffset = false ) {
>     if ( considerMapExtentOffset )
>       var mapExtentOffsetRatio = mapExtentOffset / mapCanvas.height
>     else
>       mapExtentOffsetRatio = 0
> 
>     __inputUtils.setExtentToFeature( pair, mapCanvas.mapSettings, mapExtentOffsetRatio )
>   }
> ```
> 
> and the relevant code in `InputUtils::setExtentToFeature()` Should I remove those?

Sure, if it is not used anymore, let's remove it

**Review by tomasMizera — APPROVED** [review]
